import 'dart:io';

import 'package:crypto/crypto.dart';

/// Converts an OpenCV LBP cascade XML file to compact, typed Dart constants.
void main(List<String> arguments) {
  if (arguments.length != 2) {
    stderr.writeln('Usage: dart run tool/generate_lbp_cascade.dart <cascade.xml> <output.dart>');
    exitCode = 64;
    return;
  }

  final File sourceFile = File(arguments[0]);
  final String sourceDigest = sha256
      .convert(
        sourceFile.readAsBytesSync(),
      )
      .toString();
  final String xml = sourceFile.readAsStringSync();
  final String stageSection = _section(xml, '<stages>', '</stages>');
  final String featureSection = _section(xml, '<features>', '</features>');
  final RegExp stagePattern = RegExp(
    r'<_>\s*<maxWeakCount>(\d+)</maxWeakCount>\s*<stageThreshold>([^<]+)</stageThreshold>\s*<weakClassifiers>([\s\S]*?)</weakClassifiers></_>',
  );
  final RegExp weakPattern = RegExp(
    r'<_>\s*<internalNodes>([\s\S]*?)</internalNodes>\s*<leafValues>([\s\S]*?)</leafValues></_>',
  );
  final RegExp rectanglePattern = RegExp(r'<rect>\s*([^<]+)</rect>');
  final List<int> stageWeakCounts = <int>[];
  final List<double> stageThresholds = <double>[];
  final List<int> weakFeatureIndexes = <int>[];
  final List<int> weakCategoryMasks = <int>[];
  final List<double> weakLeftValues = <double>[];
  final List<double> weakRightValues = <double>[];

  for (final RegExpMatch stageMatch in stagePattern.allMatches(stageSection)) {
    final int expectedWeakCount = int.parse(stageMatch.group(1)!);
    final List<RegExpMatch> weakMatches = weakPattern.allMatches(stageMatch.group(3)!).toList(growable: false);
    if (weakMatches.length != expectedWeakCount) {
      throw FormatException('Stage declares $expectedWeakCount weak classifiers but contains ${weakMatches.length}');
    }
    stageWeakCounts.add(expectedWeakCount);
    stageThresholds.add(double.parse(stageMatch.group(2)!.trim()));
    for (final RegExpMatch weakMatch in weakMatches) {
      final List<int> nodes = _integers(weakMatch.group(1)!);
      final List<double> leaves = _doubles(weakMatch.group(2)!);
      if (nodes.length != 11 || leaves.length != 2 || nodes[0] != 0 || nodes[1] != -1) {
        throw const FormatException('The converter only accepts depth-one, 256-category LBP stumps');
      }
      weakFeatureIndexes.add(nodes[2]);
      weakCategoryMasks.addAll(nodes.skip(3));
      weakLeftValues.add(leaves[0]);
      weakRightValues.add(leaves[1]);
    }
  }

  final List<int> featureRectangles = <int>[];
  for (final RegExpMatch rectangleMatch in rectanglePattern.allMatches(featureSection)) {
    final List<int> rectangle = _integers(rectangleMatch.group(1)!);
    if (rectangle.length != 4) {
      throw const FormatException('Every LBP feature must contain four rectangle integers');
    }
    featureRectangles.addAll(rectangle);
  }
  if (stageWeakCounts.isEmpty || featureRectangles.isEmpty || weakFeatureIndexes.isEmpty) {
    throw const FormatException('The input did not contain a supported LBP cascade');
  }
  final int declaredStageCount = int.parse(_tagValue(xml, 'stageNum'));
  if (stageWeakCounts.length != declaredStageCount) {
    throw FormatException('Expected $declaredStageCount stages, found ${stageWeakCounts.length}');
  }

  final String output =
      '''
// Generated by tool/generate_lbp_cascade.dart. Do not edit by hand.
// Source: OpenCV lbpcascade_frontalface_improved.xml (4.x branch).
// SHA-256: $sourceDigest.
// Model copyright (c) 2017 Puttemans Steven, Can Ergun, and Toon Goedeme.
// See THIRD_PARTY_NOTICES.md for copyright and license information.

/// Width of the cascade's canonical detection window.
const int lbpCascadeWidth = ${_tagValue(xml, 'width')};

/// Height of the cascade's canonical detection window.
const int lbpCascadeHeight = ${_tagValue(xml, 'height')};

/// Number of weak classifiers evaluated by each stage.
const List<int> lbpStageWeakCounts = ${_formatList(stageWeakCounts)};

/// Acceptance threshold of each cascade stage.
const List<double> lbpStageThresholds = ${_formatList(stageThresholds)};

/// Flattened x, y, width, and height values for every LBP cell feature.
const List<int> lbpFeatureRectangles = ${_formatList(featureRectangles)};

/// Feature index selected by every weak classifier.
const List<int> lbpWeakFeatureIndexes = ${_formatList(weakFeatureIndexes)};

/// Eight signed 32-bit category masks for every weak classifier.
const List<int> lbpWeakCategoryMasks = ${_formatList(weakCategoryMasks)};

/// Leaf value used when an LBP category belongs to its classifier subset.
const List<double> lbpWeakLeftValues = ${_formatList(weakLeftValues)};

/// Leaf value used when an LBP category is outside its classifier subset.
const List<double> lbpWeakRightValues = ${_formatList(weakRightValues)};
''';
  File(arguments[1]).writeAsStringSync(output);
}

/// Returns the text delimited by [opening] and [closing].
String _section(String source, String opening, String closing) {
  final int start = source.indexOf(opening);
  final int end = source.indexOf(closing, start + opening.length);
  if (start < 0 || end < 0) {
    throw FormatException('Missing XML section $opening');
  }
  return source.substring(start + opening.length, end);
}

/// Reads the trimmed text inside a simple XML [tag].
String _tagValue(String source, String tag) {
  final RegExpMatch? match = RegExp('<$tag>([^<]+)</$tag>').firstMatch(source);
  if (match == null) {
    throw FormatException('Missing XML tag $tag');
  }
  return match.group(1)!.trim();
}

/// Parses whitespace-separated signed integers.
List<int> _integers(String source) => source.trim().split(RegExp(r'\s+')).map(int.parse).toList(growable: false);

/// Parses whitespace-separated floating-point values.
List<double> _doubles(String source) => source.trim().split(RegExp(r'\s+')).map(double.parse).toList(growable: false);

/// Formats values as a readable const-list literal.
String _formatList(Iterable<num> values) {
  final List<num> materialized = values.toList(growable: false);
  if (materialized.isEmpty) {
    return '<num>[]';
  }
  final StringBuffer buffer = StringBuffer(
    '<${materialized.first is int ? 'int' : 'double'}>[\n',
  );
  for (final num value in materialized) {
    buffer.writeln('  $value,');
  }
  buffer.write(']');
  return buffer.toString();
}
